# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gHISUhoSmzlGaNIlPQ-4RRS23M2gakip
"""

#  !pip install openai

import os
import openai

def get_messages_from_completion(messages=messages, model="gpt-3.5-turbo",temperature=temperature):
  client = openai.OpenAI(api_key="your personal key")
  response = client.chat.completions.create(
      model = model,
      messages = messages,
      temperature = temperature
  )
  return response.choices[0].messages['content']

messages = [
    {'role': 'system', 'content': 'you are an instagram content creator who likes anime. \
                                    you will generate 1 recipe from a popular anime with emojis that are less than 300 characters long from different anime.'},
    {'role': 'user', 'content': 'I want to create a content on easy balanced diet.'}
]
temperatures = [0, 0.5, 0.8, 1]

for temperature in temperatures:
  content = get_messages_from_completion(messages=messages, temperature=temperature)

"""# New Section"""